#! /usr/bin/env python3
"""Keepass file checker for borgit.
With thanks to lgg on github's gist:
https://gist.github.com/lgg/e6ccc6e212d18dd2ecd8a8c116fb1e45"""
import argparse
import sys


class CheckFailure(Exception):
    """Exceptions that fail the script's health checks."""


class NotKDB(CheckFailure):
    """Error when a file is not a valid KDB."""


class UnsupportedKDB(CheckFailure):
    """Error for unsupported KDB file versions."""


class ConstraintViolated(CheckFailure):
    """Error when user-provided constraints are violated."""


def validate_signature(signature):
    """Validate the KDB file signature."""
    kdb_sig = bytes((0x03, 0xd9, 0xa2, 0x9a))
    if signature != kdb_sig:
        raise NotKDB(
            'Target file is not a valid KDB file.',
        )


def get_kdb_details(data):
    """Get information from the KDB file.
    Returns a dict containing:
      version: The version of the KDB file.
      groups: Count of groups in the KDB file.
      entries: Count of entries in the KDB file.
    """
    versions = {
        0x65: '1',
        0x66: '2-alpha',
        0x67: '2',
    }

    data_ver_byte = data[4]

    kdb_version = versions.get(data_ver_byte)

    kdb_version_signature = bytes((0xfb, 0x4b, 0xb5))
    data_version_signature = data[5:8]

    if kdb_version_signature != data_version_signature:
        raise UnsupportedKDB(
            'Unknown or corrupt KDB version encountered.'
        )
    if not kdb_version:
        raise UnsupportedKDB(
            'Unknown KDB version encountered.'
        )
    if kdb_version != '1':
        raise UnsupportedKDB(
            'Only version 1.x KDB supported currently.'
        )

    group_count = int.from_bytes(data[48:52], 'little')
    entry_count = int.from_bytes(data[52:56], 'little')

    return {
        'version': kdb_version,
        'groups': group_count,
        'entries': entry_count,
    }


def check_kdb_file(target_file, min_entries):
    """Check a KDB file is valid and meets the specified requirements."""
    with open(target_file, 'rb') as kdb_file:
        kdb_data = kdb_file.read()

    validate_signature(kdb_data[0:4])

    kdb_details = get_kdb_details(kdb_data)

    if kdb_details['entries'] < min_entries:
        raise ConstraintViolated(
            'At least {req} entries were required, '
            'but {kdb_path} had {count} entries.'.format(
                req=min_entries,
                kdb_path=target_file,
                count=kdb_details['entries'],
            )
        )


def main(args):
    """Run the checks with provided arguments."""
    parser = argparse.ArgumentParser(
        description='Check a keepass DB for borgit.',
    )

    parser.add_argument(
        '-e', '--min-entries',
        type=int,
        default=0,
        help='Minimum entries to consider this KDB healthy.',
    )
    parser.add_argument(
        'keepass_file',
        help='Path to KDB file.',
    )

    args = parser.parse_args(args)

    try:
        check_kdb_file(args.keepass_file, args.min_entries)
    except CheckFailure as err:
        sys.stderr.write(str(err) + '\n')
        sys.exit(1)


if __name__ == '__main__':
    main(sys.argv[1:])
